package com.lonnnnnng.codereader.qa

import com.lonnnnnng.codereader.model.FileType

/** @author long */
data class SampleCase(
    val assetPath: String,
    val expectedType: FileType,
)

/**
 * 模拟器覆盖清单。每个用户明确提到的语言或配置类型至少有一个真实文件。
 *
 * @author long
 */
object SampleCatalog {
    val all = listOf(
        SampleCase("samples/Main.java", FileType.JAVA),
        SampleCase("samples/service.aidl", FileType.AIDL),
        SampleCase("samples/Main.kt", FileType.KOTLIN),
        SampleCase("samples/core.clj", FileType.CLOJURE),
        SampleCase("samples/build.sbt", FileType.SCALA),
        SampleCase("samples/service.py", FileType.PYTHON),
        SampleCase("samples/main.go", FileType.GO),
        SampleCase("samples/go.mod", FileType.GO_MODULE),
        SampleCase("samples/lib.rs", FileType.RUST),
        SampleCase("samples/main.dart", FileType.DART),
        SampleCase("samples/Package.swift", FileType.SWIFT),
        SampleCase("samples/build.zig", FileType.ZIG),
        SampleCase("samples/analysis.jl", FileType.JULIA),
        SampleCase("samples/solver.f90", FileType.FORTRAN),
        SampleCase("samples/analysis.r", FileType.R),
        SampleCase("samples/index.php", FileType.PHP),
        SampleCase("samples/view.blade.php", FileType.BLADE),
        SampleCase("samples/script.pl", FileType.PERL),
        SampleCase("samples/plugin.lua", FileType.LUA),
        SampleCase("samples/init.lisp", FileType.LISP),
        SampleCase("samples/main.c", FileType.C),
        SampleCase("samples/main.cpp", FileType.CPP),
        SampleCase("samples/ViewController.m", FileType.OBJECTIVE_C),
        SampleCase("samples/Bridge.mm", FileType.OBJECTIVE_CPP),
        SampleCase("samples/startup.asm", FileType.ASSEMBLY),
        SampleCase("samples/Program.cs", FileType.CSHARP),
        SampleCase("samples/Program.fs", FileType.FSHARP),
        SampleCase("samples/Module.vb", FileType.VISUAL_BASIC),
        SampleCase("samples/App.csproj", FileType.XML),
        SampleCase("samples/Sample.sln", FileType.SOLUTION),
        SampleCase("samples/app.js", FileType.JAVASCRIPT),
        SampleCase("samples/server.mjs", FileType.JAVASCRIPT),
        SampleCase("samples/Component.jsx", FileType.JAVASCRIPT_REACT),
        SampleCase("samples/app.ts", FileType.TYPESCRIPT),
        SampleCase("samples/Component.tsx", FileType.TYPESCRIPT_REACT),
        SampleCase("samples/index.html", FileType.HTML),
        SampleCase("samples/styles.css", FileType.CSS),
        SampleCase("samples/App.vue", FileType.VUE),
        SampleCase("samples/Component.svelte", FileType.SVELTE),
        SampleCase("samples/Page.astro", FileType.ASTRO),
        SampleCase("samples/theme.scss", FileType.SCSS),
        SampleCase("samples/theme.sass", FileType.SASS),
        SampleCase("samples/theme.less", FileType.LESS),
        SampleCase("samples/partial.erb", FileType.ERB),
        SampleCase("samples/page.twig", FileType.TWIG),
        SampleCase("samples/View.razor", FileType.RAZOR),
        SampleCase("samples/config.xml", FileType.XML),
        SampleCase("samples/schema.sql", FileType.SQL),
        SampleCase("samples/message.proto", FileType.PROTOBUF),
        SampleCase("samples/schema.graphql", FileType.GRAPHQL),
        SampleCase("samples/schema.prisma", FileType.PRISMA),
        SampleCase("samples/app.toml", FileType.TOML),
        SampleCase("samples/app.properties", FileType.PROPERTIES),
        SampleCase("samples/settings.yaml", FileType.YAML),
        SampleCase("samples/config.yml", FileType.YAML),
        SampleCase("samples/legacy.ymal", FileType.YAML),
        SampleCase("samples/reader.cfg", FileType.INI),
        SampleCase("samples/data.json", FileType.JSON),
        SampleCase("samples/package.json", FileType.JSON),
        SampleCase("samples/environment.env", FileType.DOTENV),
        SampleCase("samples/README.md", FileType.MARKDOWN),
        SampleCase("samples/guide.mdx", FileType.MDX),
        SampleCase("samples/paper.tex", FileType.LATEX),
        SampleCase("samples/build.sh", FileType.SHELL),
        SampleCase("samples/deploy.ps1", FileType.POWERSHELL),
        SampleCase("samples/build.cmd", FileType.BATCH),
        SampleCase("samples/MainActivity.smali", FileType.SMALI),
        SampleCase("samples/app.rb", FileType.RUBY),
        SampleCase("samples/build.gradle", FileType.GROOVY),
        SampleCase("samples/CMakeLists.txt", FileType.CMAKE),
        SampleCase("samples/variables.hcl", FileType.HCL),
        SampleCase("samples/main.tf", FileType.TERRAFORM),
        SampleCase("samples/flake.nix", FileType.NIX),
        SampleCase("samples/nginx.conf", FileType.NGINX),
        SampleCase("samples/project.ignore", FileType.IGNORE),
        SampleCase("samples/proguard-rules.pro", FileType.PROGUARD),
        SampleCase("samples/Dockerfile", FileType.DOCKERFILE),
        SampleCase("samples/Makefile", FileType.MAKEFILE),
    )
}
